# ??????? ??? ?????. ?? ? ?????? ??? ?????.
spring.application.name=Backend

# ?????? ?? (Oracle)
## ?? ?? ?? (??? 8080 ?? ?? ??? ????? ?? ?? ? ?? ??? ?????)
## server.port=80

# Oracle ?????? ???? ??? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Oracle ??????? JDBC URL. ?? ?????? URL? ???? ???.
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
# ?????? ??? ??
spring.datasource.username=pplan
# ?????? ????
spring.datasource.password=pplan

# ??4jdbc2 ?? (?? ??? info? ??)
logging.level.root=info

# MyBatis ?? ?? ?? ??
mybatis.mapper-locations=classpath:mapper/*.xml

# Thymeleaf ??? ?? ????
spring.thymeleaf.cache=false

# ?? ??? ?? ??
# ?? ?? ?? 10MB? ??
spring.servlet.multipart.max-file-size=10MB
# ?? ?? ?? 10MB? ?? (?? ???? ??? ?? ?? ??)
spring.servlet.multipart.max-request-size=10MB
# ???? ?? ??? ??????.
spring.servlet.multipart.enabled=true

# ???? ???? ?? (???? 'mac' ????? ????? ??)
spring.profiles.active=windows

# JWT ??
# JWT ??? ???? ?? ? (?: ??? ???? ???? ? ?????.)
jwt.secret=pplanSecretKeypplanSecretKeypplanSecretKeypplanSecretKeypplanSecretKeypplanSecretKeypplanSecretKey
# JWT ??? ?? ?? (??? ??). 900,000 ???? 15?? ?????.
jwt.expiration=900000